"""Typed contract — Protocol classes defining the public API surface.

Consumers should type-annotate against these Protocols, not the concrete
classes. This enables mocking and swapping implementations freely.
"""

from __future__ import annotations

from typing import Any, Protocol

from .models.core import ExchangeStatus
from .models.responses import (
    AmendOrderResponse,
    BatchCancelOrdersResponse,
    BatchCreateOrdersResponse,
    CancelOrderResponse,
    CreateApiKeyResponse,
    CreateOrderGroupResponse,
    CreateOrderResponse,
    CreateQuoteResponse,
    CreateRFQResponse,
    DecreaseOrderResponse,
    EmptyResponse,
    GenerateApiKeyResponse,
    GetAccountApiLimitsResponse,
    GetAccountEndpointCostsResponse,
    GetApiKeysResponse,
    GetBalanceResponse,
    GetCommunicationsIDResponse,
    GetEventCandlesticksResponse,
    GetEventForecastPercentilesHistoryResponse,
    GetEventMetadataResponse,
    GetEventResponse,
    GetEventsResponse,
    GetExchangeAnnouncementsResponse,
    GetExchangeScheduleResponse,
    GetFillsResponse,
    GetFiltersBySportsResponse,
    GetGameStatsResponse,
    GetHistoricalCutoffResponse,
    GetIncentiveProgramsResponse,
    GetLiveDataResponse,
    GetLiveDatasResponse,
    GetMarketCandlesticksHistoricalResponse,
    GetMarketCandlesticksResponse,
    GetMarketOrderbookResponse,
    GetMarketOrderbooksResponse,
    GetMarketResponse,
    GetMarketsResponse,
    GetMilestoneResponse,
    GetMilestonesResponse,
    GetMultivariateEventsResponse,
    GetOrderGroupResponse,
    GetOrderGroupsResponse,
    GetOrderQueuePositionResponse,
    GetOrderQueuePositionsResponse,
    GetOrderResponse,
    GetOrdersResponse,
    GetPositionsResponse,
    GetQuoteResponse,
    GetQuotesResponse,
    GetRFQResponse,
    GetRFQsResponse,
    GetSeriesFeeChangesResponse,
    GetSeriesListResponse,
    GetSeriesResponse,
    GetSettlementsResponse,
    GetStructuredTargetResponse,
    GetStructuredTargetsResponse,
    GetTagsForSeriesCategoriesResponse,
    GetTradesResponse,
    GetUserDataTimestampResponse,
)
from .models.ws import Channel


class KalshiHttpClientProtocol(Protocol):
    """Contract for the Kalshi HTTP client."""

    # Lifecycle
    async def close(self) -> None: ...
    async def __aenter__(self) -> KalshiHttpClientProtocol: ...
    async def __aexit__(self, *args: Any) -> None: ...

    # Exchange
    async def get_exchange_status(self) -> ExchangeStatus: ...
    async def get_exchange_schedule(self) -> GetExchangeScheduleResponse: ...
    async def get_exchange_announcements(self) -> GetExchangeAnnouncementsResponse: ...
    async def get_user_data_timestamp(self) -> GetUserDataTimestampResponse: ...

    # Account
    async def get_api_limits(self) -> GetAccountApiLimitsResponse: ...
    async def get_endpoint_costs(self) -> GetAccountEndpointCostsResponse: ...

    # Orders
    async def get_orders(self, **kwargs: Any) -> GetOrdersResponse: ...
    async def get_order(self, order_id: str) -> GetOrderResponse: ...
    async def create_order(self, **kwargs: Any) -> CreateOrderResponse: ...
    async def cancel_order(self, order_id: str) -> CancelOrderResponse: ...
    async def amend_order(self, order_id: str, **kwargs: Any) -> AmendOrderResponse: ...
    async def decrease_order(self, order_id: str, **kwargs: Any) -> DecreaseOrderResponse: ...
    async def batch_create_orders(
        self, orders_list: list[dict[str, Any]]
    ) -> BatchCreateOrdersResponse: ...
    async def batch_cancel_orders(self, order_ids: list[str]) -> BatchCancelOrdersResponse: ...
    async def get_queue_positions(self, **kwargs: Any) -> GetOrderQueuePositionsResponse: ...
    async def get_order_queue_position(self, order_id: str) -> GetOrderQueuePositionResponse: ...

    # Order Groups
    async def get_order_groups(self) -> GetOrderGroupsResponse: ...
    async def create_order_group(self, contracts_limit: int) -> CreateOrderGroupResponse: ...
    async def get_order_group(self, order_group_id: str) -> GetOrderGroupResponse: ...
    async def delete_order_group(self, order_group_id: str) -> EmptyResponse: ...
    async def reset_order_group(self, order_group_id: str) -> EmptyResponse: ...
    async def trigger_order_group(
        self, order_group_id: str, **kwargs: Any
    ) -> EmptyResponse: ...
    async def update_order_group_limit(
        self, order_group_id: str, **kwargs: Any
    ) -> EmptyResponse: ...

    # Portfolio
    async def get_balance(self) -> GetBalanceResponse: ...
    async def get_positions(self, **kwargs: Any) -> GetPositionsResponse: ...
    async def get_settlements(self) -> GetSettlementsResponse: ...
    async def get_fills(self) -> GetFillsResponse: ...

    # Markets
    async def get_market(self, ticker: str) -> GetMarketResponse: ...
    async def get_markets(self, **kwargs: Any) -> GetMarketsResponse: ...
    async def get_market_orderbook(
        self, ticker: str, **kwargs: Any
    ) -> GetMarketOrderbookResponse: ...
    async def get_market_orderbooks(self, tickers: list[str]) -> GetMarketOrderbooksResponse: ...
    async def get_market_candlesticks(
        self, series_ticker: str, ticker: str, **kwargs: Any
    ) -> GetMarketCandlesticksResponse: ...
    async def get_trades(self, **kwargs: Any) -> GetTradesResponse: ...

    # Events
    async def get_event(self, event_ticker: str, **kwargs: Any) -> GetEventResponse: ...
    async def get_events(self, **kwargs: Any) -> GetEventsResponse: ...
    async def get_multivariate_events(self, **kwargs: Any) -> GetMultivariateEventsResponse: ...
    async def get_event_metadata(self, event_ticker: str) -> GetEventMetadataResponse: ...
    async def get_event_candlesticks(
        self, series_ticker: str, event_ticker: str, **kwargs: Any
    ) -> GetEventCandlesticksResponse: ...
    async def get_forecast_percentile_history(
        self, series_ticker: str, event_ticker: str, **kwargs: Any
    ) -> GetEventForecastPercentilesHistoryResponse: ...

    # Series
    async def get_series(self, series_ticker: str, **kwargs: Any) -> GetSeriesResponse: ...
    async def get_series_list(self, **kwargs: Any) -> GetSeriesListResponse: ...
    async def get_fee_changes(self, **kwargs: Any) -> GetSeriesFeeChangesResponse: ...

    # Search
    async def get_tags_by_categories(self) -> GetTagsForSeriesCategoriesResponse: ...
    async def get_filters_by_sport(self) -> GetFiltersBySportsResponse: ...

    # Historical
    async def get_historical_cutoff(self) -> GetHistoricalCutoffResponse: ...
    async def get_historical_markets(self, **kwargs: Any) -> GetMarketsResponse: ...
    async def get_historical_market(self, ticker: str) -> GetMarketResponse: ...
    async def get_historical_market_candlesticks(
        self, ticker: str, **kwargs: Any
    ) -> GetMarketCandlesticksHistoricalResponse: ...
    async def get_historical_fills(self, **kwargs: Any) -> GetFillsResponse: ...
    async def get_historical_orders(self, **kwargs: Any) -> GetOrdersResponse: ...
    async def get_historical_trades(self, **kwargs: Any) -> GetTradesResponse: ...

    # API Keys
    async def get_api_keys(self) -> GetApiKeysResponse: ...
    async def create_api_key(self, **kwargs: Any) -> CreateApiKeyResponse: ...
    async def generate_api_key(self, **kwargs: Any) -> GenerateApiKeyResponse: ...
    async def delete_api_key(self, api_key: str) -> EmptyResponse: ...

    # Communications
    async def get_communications_id(self) -> GetCommunicationsIDResponse: ...

    # RFQs
    async def get_rfqs(self, **kwargs: Any) -> GetRFQsResponse: ...
    async def create_rfq(self, **kwargs: Any) -> CreateRFQResponse: ...
    async def get_rfq(self, rfq_id: str) -> GetRFQResponse: ...
    async def delete_rfq(self, rfq_id: str) -> EmptyResponse: ...

    # Quotes
    async def get_quotes(self, **kwargs: Any) -> GetQuotesResponse: ...
    async def create_quote(self, **kwargs: Any) -> CreateQuoteResponse: ...
    async def get_quote(self, quote_id: str) -> GetQuoteResponse: ...
    async def delete_quote(self, quote_id: str) -> EmptyResponse: ...
    async def accept_quote(self, quote_id: str) -> EmptyResponse: ...

    # Live Data
    async def get_live_data(
        self, milestone_id: str, **kwargs: Any
    ) -> GetLiveDataResponse: ...
    async def get_live_data_legacy(
        self, data_type: str, milestone_id: str, **kwargs: Any
    ) -> GetLiveDataResponse: ...
    async def get_live_data_batch(
        self, milestone_ids: list[str], **kwargs: Any
    ) -> GetLiveDatasResponse: ...
    async def get_game_stats(self, milestone_id: str) -> GetGameStatsResponse: ...

    # Milestones
    async def get_milestone(self, milestone_id: str) -> GetMilestoneResponse: ...
    async def get_milestones(self, **kwargs: Any) -> GetMilestonesResponse: ...

    # Structured Targets
    async def get_structured_targets(self, **kwargs: Any) -> GetStructuredTargetsResponse: ...
    async def get_structured_target(
        self, structured_target_id: str
    ) -> GetStructuredTargetResponse: ...

    # Incentive Programs
    async def get_incentive_programs(self, **kwargs: Any) -> GetIncentiveProgramsResponse: ...


class KalshiWebSocketClientProtocol(Protocol):
    """Contract for the Kalshi WebSocket client."""

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def listener_loop(self) -> None: ...
    async def add_market(
        self, market_ticker: str, channels: list[Channel | str]
    ) -> None: ...
    async def add_markets(
        self, market_tickers: list[str], channels: list[Channel | str]
    ) -> None: ...
    async def remove_market(
        self, market_ticker: str, channels: list[Channel | str]
    ) -> None: ...
    async def unsubscribe_all(self) -> None: ...
    async def request_snapshot(
        self, market_tickers: list[str], channel: str = ...
    ) -> None: ...
    async def resubscribe_channel(self, channel_name: str) -> None: ...


class RateLimiterProtocol(Protocol):
    """Contract for rate limiting."""

    async def acquire(self, global_cost: float = 1.0, write_cost: float = 0.0) -> None: ...
    async def try_acquire(self, global_cost: float = 1.0, write_cost: float = 0.0) -> bool: ...
    async def reconfigure(self, read_rate: float, write_rate: float) -> None: ...
    def get_status(self) -> dict[str, object]: ...
