"""Typed contract — Protocol classes defining the public API surface.

Consumers should type-annotate against these Protocols, not the concrete
classes. This enables mocking and swapping implementations freely.
"""

from __future__ import annotations

from typing import Any, Dict, List, Protocol


class KalshiHttpClientProtocol(Protocol):
    """Contract for the Kalshi HTTP client."""

    # Lifecycle
    async def close(self) -> None: ...
    async def __aenter__(self) -> KalshiHttpClientProtocol: ...
    async def __aexit__(self, *args: Any) -> None: ...

    # Exchange
    async def get_exchange_status(self) -> dict[str, Any]: ...
    async def get_exchange_schedule(self) -> dict[str, Any]: ...

    # Account
    async def get_api_limits(self) -> dict[str, Any]: ...

    # Orders
    async def get_orders(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_order(self, order_id: str) -> dict[str, Any]: ...
    async def create_order(self, **kwargs: Any) -> dict[str, Any]: ...
    async def cancel_order(self, order_id: str) -> dict[str, Any]: ...
    async def amend_order(self, order_id: str, **kwargs: Any) -> dict[str, Any]: ...
    async def decrease_order(self, order_id: str, **kwargs: Any) -> dict[str, Any]: ...
    async def batch_create_orders(self, orders_list: List[Dict[str, Any]]) -> dict[str, Any]: ...
    async def batch_cancel_orders(self, order_ids: List[str]) -> dict[str, Any]: ...
    async def get_queue_positions(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_order_queue_position(self, order_id: str) -> dict[str, Any]: ...

    # Order Groups
    async def get_order_groups(self) -> dict[str, Any]: ...
    async def create_order_group(self, contracts_limit: int) -> dict[str, Any]: ...
    async def get_order_group(self, order_group_id: str) -> dict[str, Any]: ...
    async def delete_order_group(self, order_group_id: str) -> dict[str, Any]: ...
    async def reset_order_group(self, order_group_id: str) -> dict[str, Any]: ...

    # Portfolio
    async def get_balance(self) -> dict[str, Any]: ...
    async def get_positions(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_settlements(self) -> dict[str, Any]: ...
    async def get_fills(self) -> dict[str, Any]: ...

    # Markets
    async def get_market(self, ticker: str) -> dict[str, Any]: ...
    async def get_markets(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_market_orderbook(self, ticker: str) -> dict[str, Any]: ...
    async def get_trades(self, **kwargs: Any) -> dict[str, Any]: ...

    # Events
    async def get_event(self, event_ticker: str, **kwargs: Any) -> dict[str, Any]: ...
    async def get_events(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_multivariate_events(self, **kwargs: Any) -> dict[str, Any]: ...
    async def get_event_metadata(self, event_ticker: str) -> dict[str, Any]: ...

    # Series
    async def get_series(self, series_ticker: str, **kwargs: Any) -> dict[str, Any]: ...
    async def get_series_list(self, **kwargs: Any) -> dict[str, Any]: ...

    # Search
    async def get_tags_by_categories(self) -> dict[str, Any]: ...
    async def get_filters_by_sport(self) -> dict[str, Any]: ...


class KalshiWebSocketClientProtocol(Protocol):
    """Contract for the Kalshi WebSocket client."""

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def listener_loop(self) -> None: ...
    async def add_market(self, ticker: str, channels: list[str]) -> None: ...
    async def add_markets(self, tickers: list[str], channels: list[str]) -> None: ...
    async def remove_market(self, ticker: str, channels: list[str]) -> None: ...
    async def unsubscribe_all(self) -> None: ...
    async def request_snapshot(self, market_tickers: list[str], channel: str = ...) -> None: ...


class RateLimiterProtocol(Protocol):
    """Contract for rate limiting."""

    async def acquire(self, global_cost: float = 1.0, write_cost: float = 0.0) -> None: ...
    async def try_acquire(self, global_cost: float = 1.0, write_cost: float = 0.0) -> bool: ...
    async def reconfigure(self, read_rate: float, write_rate: float) -> None: ...
    def get_status(self) -> dict[str, object]: ...
