"""Core domain models generated from the Kalshi OpenAPI spec."""

# NOTE: Auto-generated by tools/generate_models.py — do not edit manually.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from .enums import OrderStatus, SelfTradePreventionType


class BidAskDistributionHistorical(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    open: str
    low: str
    high: str
    close: str


class PriceDistributionHistorical(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    open: str | None = None
    low: str | None = None
    high: str | None = None
    close: str | None = None
    mean: str | None = None
    previous: str | None = None


class MarketCandlestickHistorical(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    end_period_ts: int
    yes_bid: BidAskDistributionHistorical
    yes_ask: BidAskDistributionHistorical
    price: PriceDistributionHistorical
    volume: str
    open_interest: str


class ApiKey(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_key_id: str
    name: str
    scopes: list[str]


class ScopeList(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    scopes: list[str]


class SportFilterDetails(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    scopes: list[str]
    competitions: dict[str, ScopeList]


class EndpointTokenCost(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    method: str
    path: str
    cost: int


class ExchangeStatus(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    exchange_active: bool
    trading_active: bool
    exchange_estimated_resume_time: str | None = None


class Announcement(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    message: str
    delivery_time: str
    status: str


class MaintenanceWindow(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    start_datetime: str
    end_datetime: str


class DailySchedule(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    open_time: str
    close_time: str


class WeeklySchedule(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    start_time: str
    end_time: str
    monday: list[DailySchedule]
    tuesday: list[DailySchedule]
    wednesday: list[DailySchedule]
    thursday: list[DailySchedule]
    friday: list[DailySchedule]
    saturday: list[DailySchedule]
    sunday: list[DailySchedule]


class Schedule(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    standard_hours: list[WeeklySchedule]
    maintenance_windows: list[MaintenanceWindow]


class BidAskDistribution(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    open_dollars: str
    low_dollars: str
    high_dollars: str
    close_dollars: str


class PriceDistribution(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    open_dollars: str | None = None
    low_dollars: str | None = None
    high_dollars: str | None = None
    close_dollars: str | None = None
    mean_dollars: str | None = None
    previous_dollars: str | None = None
    min_dollars: str | None = None
    max_dollars: str | None = None


class MarketCandlestick(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    end_period_ts: int
    yes_bid: BidAskDistribution
    yes_ask: BidAskDistribution
    price: PriceDistribution
    volume_fp: str
    open_interest_fp: str


class LiveData(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    details: dict[str, Any]
    milestone_id: str


class PlayByPlay(BaseModel):
    """Play-by-play data organized by period."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    periods: list[dict[str, Any]] | None = None


class Settlement(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    event_ticker: str
    market_result: str
    yes_count_fp: str
    yes_total_cost_dollars: str
    no_count_fp: str
    no_total_cost_dollars: str
    revenue: int
    settled_time: str
    fee_cost: str
    value: int | None = None


class Order(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    user_id: str
    client_order_id: str
    ticker: str
    side: str
    action: str
    type_: str = Field(..., alias="type")
    status: OrderStatus
    yes_price_dollars: str
    no_price_dollars: str
    fill_count_fp: str
    remaining_count_fp: str
    initial_count_fp: str
    taker_fill_cost_dollars: str
    maker_fill_cost_dollars: str
    taker_fees_dollars: str
    maker_fees_dollars: str
    expiration_time: str | None = None
    created_time: str | None = None
    last_update_time: str | None = None
    self_trade_prevention_type: SelfTradePreventionType | None = None
    order_group_id: str | None = None
    cancel_order_on_pause: bool | None = None
    subaccount_number: int | None = None


class Milestone(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str
    category: str
    type_: str = Field(..., alias="type")
    start_date: str
    end_date: str | None = None
    related_event_tickers: list[str]
    title: str
    notification_message: str
    source_id: str | None = None
    source_ids: dict[str, str] | None = None
    details: dict[str, Any]
    primary_event_tickers: list[str]
    last_updated_ts: str


class OrderQueuePosition(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    market_ticker: str
    queue_position_fp: str


class MarketPosition(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    total_traded_dollars: str
    position_fp: str
    market_exposure_dollars: str
    realized_pnl_dollars: str
    fees_paid_dollars: str
    last_updated_ts: str


class EventPosition(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str
    total_cost_dollars: str
    total_cost_shares_fp: str
    event_exposure_dollars: str
    realized_pnl_dollars: str
    fees_paid_dollars: str


class Trade(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    trade_id: str
    ticker: str
    count_fp: str
    yes_price_dollars: str
    no_price_dollars: str
    taker_side: str
    created_time: str


class IncentiveProgram(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str
    market_id: str
    market_ticker: str
    incentive_type: str
    start_date: str
    end_date: str
    period_reward: int
    paid_out: bool
    discount_factor_bps: int | None = None
    target_size_fp: str | None = None


class Fill(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    fill_id: str
    trade_id: str
    order_id: str
    ticker: str
    market_ticker: str
    side: str
    action: str
    count_fp: str
    yes_price_dollars: str
    no_price_dollars: str
    is_taker: bool
    created_time: str | None = None
    fee_cost: str
    subaccount_number: int | None = None
    ts: int | None = None


class StructuredTarget(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str | None = None
    name: str | None = None
    type_: str | None = Field(None, alias="type")
    details: dict[str, Any] | None = None
    source_id: str | None = None
    source_ids: dict[str, str] | None = None
    last_updated_ts: str | None = None


class OrderGroup(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str
    contracts_limit_fp: str | None = None
    is_auto_cancel_enabled: bool


class MveSelectedLeg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str | None = None
    market_ticker: str | None = None
    side: str | None = None
    yes_settlement_value_dollars: str | None = None


class RFQ(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str
    creator_id: str
    market_ticker: str
    contracts_fp: str
    target_cost_dollars: str | None = None
    status: str
    created_ts: str
    mve_collection_ticker: str | None = None
    mve_selected_legs: list[MveSelectedLeg] | None = None
    rest_remainder: bool | None = None
    cancellation_reason: str | None = None
    creator_user_id: str | None = None
    creator_subaccount: int | None = None
    cancelled_ts: str | None = None
    updated_ts: str | None = None


class Quote(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str
    rfq_id: str
    creator_id: str
    rfq_creator_id: str
    market_ticker: str
    contracts_fp: str
    yes_bid_dollars: str
    no_bid_dollars: str
    created_ts: str
    updated_ts: str
    status: str
    accepted_side: str | None = None
    accepted_ts: str | None = None
    confirmed_ts: str | None = None
    executed_ts: str | None = None
    cancelled_ts: str | None = None
    rest_remainder: bool | None = None
    cancellation_reason: str | None = None
    creator_user_id: str | None = None
    rfq_creator_user_id: str | None = None
    rfq_target_cost_dollars: str | None = None
    rfq_creator_order_id: str | None = None
    creator_order_id: str | None = None
    creator_subaccount: int | None = None
    rfq_creator_subaccount: int | None = None
    yes_contracts_fp: str | None = None
    no_contracts_fp: str | None = None


class BatchCancelOrdersRequestOrder(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    subaccount: int | None = None


class AssociatedEvent(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    is_yes_only: bool
    size_max: int | None = None
    size_min: int | None = None
    active_quoters: list[str]


class MultivariateEventCollection(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    collection_ticker: str
    series_ticker: str
    title: str
    description: str
    open_date: str
    close_date: str
    associated_events: list[AssociatedEvent]
    associated_event_tickers: list[str]
    is_ordered: bool
    is_single_market_per_event: bool
    is_all_yes: bool
    size_min: int
    size_max: int
    functional_description: str


class TickerPair(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    event_ticker: str
    side: str


class LookupPoint(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str
    market_ticker: str
    selected_markets: list[TickerPair]
    last_queried_ts: str


PriceLevelDollarsCountFp = list[str]


class OrderbookCountFp(BaseModel):
    """Orderbook with fixed-point contract counts (fp) in all dollar price levels."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    yes_dollars: list[PriceLevelDollarsCountFp]
    no_dollars: list[PriceLevelDollarsCountFp]


class MarketOrderbookFp(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    orderbook_fp: OrderbookCountFp


class MarketMetadata(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    image_url: str
    color_code: str


class PercentilePoint(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    percentile: int
    raw_numerical_forecast: float
    numerical_forecast: float
    formatted_forecast: str


class ForecastPercentilesPoint(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str
    end_period_ts: int
    period_interval: int
    percentile_points: list[PercentilePoint]


class PriceRange(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    start: str
    end: str
    step: str


class Market(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    event_ticker: str
    market_type: str
    yes_sub_title: str
    no_sub_title: str
    created_time: str
    updated_time: str
    open_time: str
    close_time: str
    expected_expiration_time: str | None = None
    latest_expiration_time: str
    settlement_timer_seconds: int
    status: str
    yes_bid_dollars: str
    yes_bid_size_fp: str
    yes_ask_dollars: str
    yes_ask_size_fp: str
    no_bid_dollars: str
    no_ask_dollars: str
    last_price_dollars: str
    volume_fp: str
    volume_24h_fp: str
    result: str
    can_close_early: bool
    fractional_trading_enabled: bool
    open_interest_fp: str
    notional_value_dollars: str
    previous_yes_bid_dollars: str
    previous_yes_ask_dollars: str
    previous_price_dollars: str
    settlement_value_dollars: str | None = None
    settlement_ts: str | None = None
    expiration_value: str
    occurrence_datetime: str | None = None
    fee_waiver_expiration_time: str | None = None
    early_close_condition: str | None = None
    strike_type: str | None = None
    floor_strike: float | None = None
    cap_strike: float | None = None
    functional_strike: str | None = None
    custom_strike: dict[str, Any] | None = None
    rules_primary: str
    rules_secondary: str
    mve_collection_ticker: str | None = None
    mve_selected_legs: list[MveSelectedLeg] | None = None
    primary_participant_key: str | None = None
    price_level_structure: str
    price_ranges: list[PriceRange]
    is_provisional: bool | None = None


class EventData(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str
    series_ticker: str
    sub_title: str
    title: str
    collateral_return_type: str
    mutually_exclusive: bool
    strike_date: str | None = None
    strike_period: str | None = None
    markets: list[Market] | None = None
    available_on_brokers: bool
    product_metadata: dict[str, Any] | None = None
    last_updated_ts: str | None = None


class SettlementSource(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str | None = None
    url: str | None = None


class Series(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    frequency: str
    title: str
    category: str
    tags: list[str]
    settlement_sources: list[SettlementSource]
    contract_url: str
    contract_terms_url: str
    product_metadata: dict[str, Any] | None = None
    fee_type: str
    fee_multiplier: float
    additional_prohibitions: list[str]
    volume_fp: str | None = None
    last_updated_ts: str | None = None


class SeriesFeeChange(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str
    series_ticker: str
    fee_type: str
    fee_multiplier: float
    scheduled_ts: str
