"""Enum types generated from the Kalshi OpenAPI spec."""

# NOTE: Auto-generated by tools/generate_models.py — do not edit manually.

from __future__ import annotations

from enum import Enum


class ExchangeInstance(str, Enum):
    """The exchange instance type"""

    EVENT_CONTRACT = "event_contract"
    MARGINED = "margined"


class OrderStatus(str, Enum):
    """The status of an order"""

    RESTING = "resting"
    CANCELED = "canceled"
    EXECUTED = "executed"


class SelfTradePreventionType(str, Enum):
    """The self-trade prevention type for orders"""

    TAKER_AT_CROSS = "taker_at_cross"
    MAKER = "maker"
