"""Request models generated from the Kalshi OpenAPI spec."""

# NOTE: Auto-generated by tools/generate_models.py — do not edit manually.

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .enums import SelfTradePreventionType
from .core import BatchCancelOrdersRequestOrder, TickerPair


class CreateApiKeyRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    public_key: str
    scopes: list[str] | None = None


class GenerateApiKeyRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    scopes: list[str] | None = None


class ApplySubaccountTransferRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    client_transfer_id: str
    from_subaccount: int
    to_subaccount: int
    amount_cents: int


class UpdateSubaccountNettingRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount_number: int
    enabled: bool


class CreateOrderGroupRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount: int | None = None
    contracts_limit: int | None = None
    contracts_limit_fp: str | None = None


class UpdateOrderGroupLimitRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    contracts_limit: int | None = None
    contracts_limit_fp: str | None = None


class CreateRFQRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    contracts: int | None = None
    contracts_fp: str | None = None
    target_cost_dollars: str | None = None
    rest_remainder: bool
    replace_existing: bool | None = None
    subtrader_id: str | None = None
    subaccount: int | None = None


class CreateQuoteRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rfq_id: str
    yes_bid: str
    no_bid: str
    rest_remainder: bool
    subaccount: int | None = None


class AcceptQuoteRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    accepted_side: str


class CreateOrderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    client_order_id: str | None = None
    side: str
    action: str
    count: int | None = None
    count_fp: str | None = None
    yes_price: int | None = None
    no_price: int | None = None
    yes_price_dollars: str | None = None
    no_price_dollars: str | None = None
    expiration_ts: int | None = None
    time_in_force: str | None = None
    buy_max_cost: int | None = None
    post_only: bool | None = None
    reduce_only: bool | None = None
    sell_position_floor: int | None = None
    self_trade_prevention_type: SelfTradePreventionType | None = None
    order_group_id: str | None = None
    cancel_order_on_pause: bool | None = None
    subaccount: int | None = None


class BatchCreateOrdersRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[CreateOrderRequest]


class BatchCancelOrdersRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[BatchCancelOrdersRequestOrder] | None = None


class AmendOrderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount: int | None = None
    ticker: str
    side: str
    action: str
    client_order_id: str | None = None
    updated_client_order_id: str | None = None
    yes_price: int | None = None
    no_price: int | None = None
    yes_price_dollars: str | None = None
    no_price_dollars: str | None = None
    count: int | None = None
    count_fp: str | None = None


class DecreaseOrderRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount: int | None = None
    reduce_by: int | None = None
    reduce_by_fp: str | None = None
    reduce_to: int | None = None
    reduce_to_fp: str | None = None


class LookupTickersForMarketInMultivariateEventCollectionRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    selected_markets: list[TickerPair]


class CreateMarketInMultivariateEventCollectionRequest(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    selected_markets: list[TickerPair]
    with_market_payload: bool | None = None
