"""Response models generated from the Kalshi OpenAPI spec."""

# NOTE: Auto-generated by tools/generate_models.py — do not edit manually.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from .core import Announcement, ApiKey, BucketLimit, Deposit, EndpointTokenCost, EventData, EventPosition, ExchangeIndex, Fill, ForecastPercentilesPoint, IncentiveProgram, IndexedBalance, LiveData, LookupPoint, Market, MarketCandlestick, MarketCandlestickHistorical, MarketMetadata, MarketOrderbookFp, MarketPosition, Milestone, MultivariateEventCollection, Order, OrderGroup, OrderQueuePosition, OrderbookCountFp, PlayByPlay, Quote, RFQ, Schedule, Series, SeriesFeeChange, Settlement, SettlementSource, SportFilterDetails, StructuredTarget, Trade, Withdrawal


class GetMarketCandlesticksHistoricalResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str = Field(..., description="Unique identifier for the market.")
    candlesticks: list[MarketCandlestickHistorical] = Field(..., description="Array of candlestick data points for the specified time range.")


class ErrorResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    code: str | None = Field(None, description="Error code")
    message: str | None = Field(None, description="Human-readable error message")
    details: str | None = Field(None, description="Additional details about the error, if available")
    service: str | None = Field(None, description="The name of the service that generated the error")


class GetApiKeysResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_keys: list[ApiKey] = Field(..., description="List of all API keys associated with the user")


class CreateApiKeyResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_key_id: str = Field(..., description="Unique identifier for the newly created API key")


class GenerateApiKeyResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_key_id: str = Field(..., description="Unique identifier for the newly generated API key")
    private_key: str = Field(..., description="RSA private key in PEM format. This must be stored securely and cannot be retrieved again after this response")


class GetTagsForSeriesCategoriesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tags_by_categories: dict[str, list[str]] = Field(..., description="Mapping of series categories to their associated tags")


class GetFiltersBySportsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    filters_by_sports: dict[str, SportFilterDetails] = Field(..., description="Mapping of sports to their filter details")
    sport_ordering: list[str] = Field(..., description="Ordered list of sports for display")


class GetAccountApiLimitsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    usage_tier: str = Field(..., description="User's API usage tier.")
    read: BucketLimit
    write: BucketLimit


class GetAccountEndpointCostsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    default_cost: int = Field(..., description="Default token cost applied to endpoints that are not listed in `endpoint_costs`. This is currently 10.")
    endpoint_costs: list[EndpointTokenCost] = Field(..., description="API v2 endpoints whose configured token cost differs from `default_cost`. Endpoints that use the default cost are omitted.")


class GetExchangeAnnouncementsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    announcements: list[Announcement] = Field(..., description="A list of exchange-wide announcements.")


class GetExchangeScheduleResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    schedule: Schedule


class GetHistoricalCutoffResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_settled_ts: str = Field(..., description="Cutoff based on **market settlement time**. Markets and their candlesticks that settled before this timestamp must be accessed via `GET /historical/markets` and `GET /historical/markets/{ticker}/candlesticks`.")
    trades_created_ts: str = Field(..., description="Cutoff based on **trade fill time**. Fills that occurred before this timestamp must be accessed via `GET /historical/fills`.")
    orders_updated_ts: str = Field(..., description="Cutoff based on **order cancellation or execution time**. Orders canceled or fully executed before this timestamp must be accessed via `GET /historical/orders`. Resting (active) orders are always available in `GET /portfolio/orders`.")


class GetUserDataTimestampResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    as_of_time: str = Field(..., description="Timestamp when user data was last updated.")


class GetMarketCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str = Field(..., description="Unique identifier for the market.")
    candlesticks: list[MarketCandlestick] = Field(..., description="Array of candlestick data points for the specified time range.")


class GetEventCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_tickers: list[str] = Field(..., description="Array of market tickers in the event.")
    market_candlesticks: list[list[MarketCandlestick]] = Field(..., description="Array of market candlestick arrays, one for each market in the event.")
    adjusted_end_ts: int = Field(..., description="Adjusted end timestamp if the requested candlesticks would be larger than maxAggregateCandidates.")


class MarketCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str = Field(..., description="Market ticker string (e.g., 'INXD-24JAN01').")
    candlesticks: list[MarketCandlestick] = Field(..., description="Array of candlestick data points for the market. Includes an initial data point at the start timestamp when available.")


class BatchGetMarketCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    markets: list[MarketCandlesticksResponse] = Field(..., description="Array of market candlestick data, one entry per requested market.")


class GetLiveDataResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    live_data: LiveData


class GetLiveDatasResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    live_datas: list[LiveData] | None = None


class GetGameStatsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    pbp: PlayByPlay | None = None


class GetBalanceResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    balance: int = Field(..., description="Member's available balance in cents. This represents the amount available for trading.")
    balance_dollars: str | None = Field(None, description="Member's available balance as a fixed-point dollar string. This represents the amount available for trading.")
    portfolio_value: int = Field(..., description="Member's portfolio value in cents. This is the current value of all positions held.")
    updated_ts: int = Field(..., description="Unix timestamp of the last update to the balance.")
    balance_breakdown: list[IndexedBalance] | None = Field(None, description="Balance broken down per exchange index.")


class CreateSubaccountResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount_number: int = Field(..., description="The sequential number assigned to this subaccount (1-32).")


class ApplySubaccountTransferResponse(BaseModel):
    """Empty response indicating successful transfer."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    pass


class GetSubaccountBalancesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount_balances: list[Any]


class GetSubaccountTransfersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    transfers: list[Any]
    cursor: str | None = Field(None, description="Cursor for the next page of results.")


class GetSubaccountNettingResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    netting_configs: list[Any]


class GetSettlementsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    settlements: list[Settlement]
    cursor: str | None = None


class GetPortfolioRestingOrderTotalValueResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    total_resting_order_value: int = Field(..., description="Total value of resting orders in cents")


class GetDepositsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    deposits: list[Deposit]
    cursor: str | None = None


class GetWithdrawalsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    withdrawals: list[Withdrawal]
    cursor: str | None = None


class GetMilestoneResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    milestone: Milestone = Field(..., description="The milestone data.")


class GetMilestonesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    milestones: list[Milestone] = Field(..., description="List of milestones.")
    cursor: str | None = Field(None, description="Cursor for pagination.")


class GetOrdersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[Order]
    cursor: str


class GetOrderQueuePositionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    queue_position_fp: str = Field(..., description="The number of preceding shares before the order in the queue.")


class GetOrderQueuePositionsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    queue_positions: list[OrderQueuePosition] | None = Field(None, description="Queue positions for all matching orders")


class GetPositionsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    cursor: str | None = Field(None, description="The Cursor represents a pointer to the next page of records in the pagination. Use the value returned here in the cursor query parameter for this end-point to get the next page containing limit records. An empty value of this field indicates there is no next page.")
    market_positions: list[MarketPosition] = Field(..., description="List of market positions")
    event_positions: list[EventPosition] = Field(..., description="List of event positions")


class GetIncentiveProgramsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    incentive_programs: list[IncentiveProgram]
    next_cursor: str | None = Field(None, description="Cursor for pagination to get the next page of results")


class GetTradesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    trades: list[Trade]
    cursor: str


class GetFillsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    fills: list[Fill]
    cursor: str


class GetStructuredTargetsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    structured_targets: list[StructuredTarget] | None = None
    cursor: str | None = Field(None, description="Pagination cursor for the next page. Empty if there are no more results.")


class GetStructuredTargetResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    structured_target: StructuredTarget | None = None


class EmptyResponse(BaseModel):
    """An empty response body"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    pass


class GetOrderGroupsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_groups: list[OrderGroup] | None = None


class GetOrderGroupResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    is_auto_cancel_enabled: bool = Field(..., description="Whether auto-cancel is enabled for this order group")
    contracts_limit_fp: str | None = Field(None, description="String representation of the current maximum contracts allowed over a rolling 15-second window.")
    orders: list[str] = Field(..., description="List of order IDs that belong to this order group")
    exchange_index: ExchangeIndex | None = None


class CreateOrderGroupResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_group_id: str = Field(..., description="The unique identifier for the created order group")
    subaccount: int | None = Field(None, description="Subaccount number that owns the created order group (0 for primary, 1-32 for subaccounts).")
    exchange_index: ExchangeIndex | None = None


class GetCommunicationsIDResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    communications_id: str = Field(..., description="A public communications ID which is used to identify the user")


class GetRFQsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rfqs: list[RFQ] = Field(..., description="List of RFQs matching the query criteria")
    cursor: str | None = Field(None, description="Cursor for pagination to get the next page of results")


class GetRFQResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rfq: RFQ = Field(..., description="The details of the requested RFQ")


class CreateRFQResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(..., description="The ID of the newly created RFQ")


class GetQuotesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quotes: list[Quote] = Field(..., description="List of quotes matching the query criteria")
    cursor: str | None = Field(None, description="Cursor for pagination to get the next page of results")


class GetQuoteResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quote: Quote = Field(..., description="The details of the requested quote")


class CreateQuoteResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(..., description="The ID of the newly created quote")


class GetOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order


class CreateOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order


class BatchCreateOrdersIndividualResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    client_order_id: str | None = None
    order: Order | None = None
    error: ErrorResponse | None = None


class BatchCreateOrdersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[BatchCreateOrdersIndividualResponse]


class BatchCancelOrdersIndividualResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str = Field(..., description="The order ID to identify which order had an error during batch cancellation")
    order: Order | None = None
    reduced_by_fp: str = Field(..., description="String representation of the number of contracts that were successfully canceled from this order")
    error: ErrorResponse | None = None


class BatchCancelOrdersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[BatchCancelOrdersIndividualResponse]


class CancelOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order
    reduced_by_fp: str = Field(..., description="String representation of the number of contracts that were successfully canceled from this order")


class AmendOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    old_order: Order = Field(..., description="The order before amendment")
    order: Order = Field(..., description="The order after amendment")


class DecreaseOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order


class CreateOrderV2Response(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    client_order_id: str | None = None
    fill_count: str = Field(..., description="Number of contracts filled immediately upon placement.")
    remaining_count: str = Field(..., description="Number of contracts remaining after placement. For IOC orders, this reflects the final state after unfilled contracts are canceled.")
    average_fill_price: str | None = Field(None, description="Volume-weighted average fill price. Only present when fill_count > 0.")
    average_fee_paid: str | None = Field(None, description="Volume-weighted average fee paid per contract for fills resulting from this request. Only present when fill_count > 0.")
    ts_ms: int = Field(..., description="Matching engine timestamp at which the order was processed, as Unix epoch milliseconds.")


class CancelOrderV2Response(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    client_order_id: str | None = None
    reduced_by: str = Field(..., description="Number of contracts that were canceled (i.e. the remaining count at time of cancellation).")
    ts_ms: int = Field(..., description="Matching engine timestamp at which the cancellation was processed, as Unix epoch milliseconds.")


class DecreaseOrderV2Response(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    client_order_id: str | None = None
    remaining_count: str = Field(..., description="Number of contracts remaining after the decrease.")
    ts_ms: int = Field(..., description="Matching engine timestamp at which the decrease was processed, as Unix epoch milliseconds.")


class AmendOrderV2Response(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    client_order_id: str | None = None
    remaining_count: str | None = Field(None, description="Number of resting contracts remaining after the amend. This is the actual post-amend resting quantity, not the request's total/max fillable count. Only present when the amend caused a fill or changed the resting size.")
    fill_count: str | None = Field(None, description="Number of contracts filled as a result of the amend crossing the book. Only present when fills occurred or remaining size changed.")
    average_fill_price: str | None = Field(None, description="Volume-weighted average fill price for fills resulting from the amend. Only present when fills occurred.")
    average_fee_paid: str | None = Field(None, description="Volume-weighted average fee paid per contract for fills resulting from the amend. Only present when fills occurred.")
    ts_ms: int = Field(..., description="Matching engine timestamp at which the amend was processed, as Unix epoch milliseconds.")


class BatchCreateOrdersV2Response(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[dict[str, Any]]


class BatchCancelOrdersV2Response(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[dict[str, Any]]


class GetMultivariateEventCollectionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    multivariate_contract: MultivariateEventCollection = Field(..., description="The multivariate event collection.")


class GetMultivariateEventCollectionsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    multivariate_contracts: list[MultivariateEventCollection] = Field(..., description="List of multivariate event collections.")
    cursor: str | None = Field(None, description="The Cursor represents a pointer to the next page of records in the pagination. Use the value returned here in the cursor query parameter for this end-point to get the next page containing limit records. An empty value of this field indicates there is no next page.")


class LookupTickersForMarketInMultivariateEventCollectionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str = Field(..., description="Event ticker for the looked up market.")
    market_ticker: str = Field(..., description="Market ticker for the looked up market.")


class GetMultivariateEventCollectionLookupHistoryResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    lookup_points: list[LookupPoint] = Field(..., description="List of recent lookup points in the collection.")


class CreateMarketInMultivariateEventCollectionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str = Field(..., description="Event ticker for the created market.")
    market_ticker: str = Field(..., description="Market ticker for the created market.")
    market: Market | None = Field(None, description="Market payload of the created market.")


class GetMarketOrderbooksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orderbooks: list[MarketOrderbookFp]


class GetMarketOrderbookResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orderbook_fp: OrderbookCountFp = Field(..., description="Orderbook with fixed-point contract counts (fp) in all price levels.")


class GetEventsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    events: list[EventData] = Field(..., description="Array of events matching the query criteria.")
    milestones: list[Milestone] | None = Field(None, description="Array of milestones related to the events.")
    cursor: str = Field(..., description="Pagination cursor for the next page. Empty if there are no more results.")


class GetMultivariateEventsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    events: list[EventData] = Field(..., description="Array of multivariate events matching the query criteria.")
    cursor: str = Field(..., description="Pagination cursor for the next page. Empty if there are no more results.")


class GetEventResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event: EventData = Field(..., description="Data for the event.")
    markets: list[Market] = Field(..., description="Data for the markets in this event. This field is deprecated in favour of the \"markets\" field inside the event. Which will be filled with the same value if you use the query parameter \"with_nested_markets=true\".")


class GetEventMetadataResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    image_url: str = Field(..., description="A path to an image that represents this event.")
    featured_image_url: str | None = Field(None, description="A path to an image that represents the image of the featured market.")
    market_details: list[MarketMetadata] = Field(..., description="Metadata for the markets in this event.")
    settlement_sources: list[SettlementSource] = Field(..., description="A list of settlement sources for this event.")
    competition: str | None = Field(None, description="Event competition.")
    competition_scope: str | None = Field(None, description="Event scope, based on the competition.")


class GetEventForecastPercentilesHistoryResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    forecast_history: list[ForecastPercentilesPoint] = Field(..., description="Array of forecast percentile data points over time.")


class GetSeriesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    series: Series


class GetSeriesListResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    series: list[Series]


class GetSeriesFeeChangesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    series_fee_change_arr: list[SeriesFeeChange]


class GetMarketsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    markets: list[Market]
    cursor: str


class GetMarketResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market: Market
