"""Response models generated from the Kalshi OpenAPI spec."""

# NOTE: Auto-generated by tools/generate_models.py — do not edit manually.

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from .core import Announcement, ApiKey, EndpointTokenCost, EventData, EventPosition, Fill, ForecastPercentilesPoint, IncentiveProgram, LiveData, LookupPoint, Market, MarketCandlestick, MarketCandlestickHistorical, MarketMetadata, MarketOrderbookFp, MarketPosition, Milestone, MultivariateEventCollection, Order, OrderGroup, OrderQueuePosition, OrderbookCountFp, PlayByPlay, Quote, RFQ, Schedule, Series, SeriesFeeChange, Settlement, SettlementSource, SportFilterDetails, StructuredTarget, Trade


class GetMarketCandlesticksHistoricalResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    candlesticks: list[MarketCandlestickHistorical]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    code: str | None = None
    message: str | None = None
    details: str | None = None
    service: str | None = None


class GetApiKeysResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_keys: list[ApiKey]


class CreateApiKeyResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_key_id: str


class GenerateApiKeyResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    api_key_id: str
    private_key: str


class GetTagsForSeriesCategoriesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tags_by_categories: dict[str, list[str]]


class GetFiltersBySportsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    filters_by_sports: dict[str, SportFilterDetails]
    sport_ordering: list[str]


class GetAccountApiLimitsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    usage_tier: str
    read_limit: int
    write_limit: int


class GetAccountEndpointCostsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    default_cost: int
    endpoint_costs: list[EndpointTokenCost]


class GetExchangeAnnouncementsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    announcements: list[Announcement]


class GetExchangeScheduleResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    schedule: Schedule


class GetHistoricalCutoffResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_settled_ts: str
    trades_created_ts: str
    orders_updated_ts: str


class GetUserDataTimestampResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    as_of_time: str


class GetMarketCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ticker: str
    candlesticks: list[MarketCandlestick]


class GetEventCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_tickers: list[str]
    market_candlesticks: list[list[MarketCandlestick]]
    adjusted_end_ts: int


class MarketCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    candlesticks: list[MarketCandlestick]


class BatchGetMarketCandlesticksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    markets: list[MarketCandlesticksResponse]


class GetLiveDataResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    live_data: LiveData


class GetLiveDatasResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    live_datas: list[LiveData]


class GetGameStatsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    pbp: PlayByPlay | None = None


class GetBalanceResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    balance: int
    portfolio_value: int
    updated_ts: int


class CreateSubaccountResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount_number: int


class ApplySubaccountTransferResponse(BaseModel):
    """Empty response indicating successful transfer."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    pass


class GetSubaccountBalancesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    subaccount_balances: list[Any]


class GetSubaccountTransfersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    transfers: list[Any]
    cursor: str | None = None


class GetSubaccountNettingResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    netting_configs: list[Any]


class GetSettlementsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    settlements: list[Settlement]
    cursor: str | None = None


class GetPortfolioRestingOrderTotalValueResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    total_resting_order_value: int


class GetMilestoneResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    milestone: Milestone


class GetMilestonesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    milestones: list[Milestone]
    cursor: str | None = None


class GetOrdersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[Order]
    cursor: str


class GetOrderQueuePositionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    queue_position_fp: str


class GetOrderQueuePositionsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    queue_positions: list[OrderQueuePosition]


class GetPositionsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    cursor: str | None = None
    market_positions: list[MarketPosition]
    event_positions: list[EventPosition]


class GetIncentiveProgramsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    incentive_programs: list[IncentiveProgram]
    next_cursor: str | None = None


class GetTradesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    trades: list[Trade]
    cursor: str


class GetFillsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    fills: list[Fill]
    cursor: str


class GetStructuredTargetsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    structured_targets: list[StructuredTarget] | None = None
    cursor: str | None = None


class GetStructuredTargetResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    structured_target: StructuredTarget | None = None


class EmptyResponse(BaseModel):
    """An empty response body"""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    pass


class GetOrderGroupsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_groups: list[OrderGroup] | None = None


class GetOrderGroupResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    is_auto_cancel_enabled: bool
    contracts_limit_fp: str | None = None
    orders: list[str]


class CreateOrderGroupResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_group_id: str


class GetCommunicationsIDResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    communications_id: str


class GetRFQsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rfqs: list[RFQ]
    cursor: str | None = None


class GetRFQResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rfq: RFQ


class CreateRFQResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str


class GetQuotesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quotes: list[Quote]
    cursor: str | None = None


class GetQuoteResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quote: Quote


class CreateQuoteResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str


class GetOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order


class CreateOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order


class BatchCreateOrdersIndividualResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    client_order_id: str | None = None
    order: Order | None = None
    error: ErrorResponse | None = None


class BatchCreateOrdersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[BatchCreateOrdersIndividualResponse]


class BatchCancelOrdersIndividualResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str
    order: Order | None = None
    reduced_by_fp: str
    error: ErrorResponse | None = None


class BatchCancelOrdersResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orders: list[BatchCancelOrdersIndividualResponse]


class CancelOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order
    reduced_by_fp: str


class AmendOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    old_order: Order
    order: Order


class DecreaseOrderResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order: Order


class GetMultivariateEventCollectionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    multivariate_contract: MultivariateEventCollection


class GetMultivariateEventCollectionsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    multivariate_contracts: list[MultivariateEventCollection]
    cursor: str | None = None


class LookupTickersForMarketInMultivariateEventCollectionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str
    market_ticker: str


class GetMultivariateEventCollectionLookupHistoryResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    lookup_points: list[LookupPoint]


class CreateMarketInMultivariateEventCollectionResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str
    market_ticker: str
    market: Market | None = None


class GetMarketOrderbooksResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orderbooks: list[MarketOrderbookFp]


class GetMarketOrderbookResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    orderbook_fp: OrderbookCountFp


class GetEventsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    events: list[EventData]
    milestones: list[Milestone] | None = None
    cursor: str


class GetMultivariateEventsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    events: list[EventData]
    cursor: str


class GetEventResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event: EventData
    markets: list[Market]


class GetEventMetadataResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    image_url: str
    featured_image_url: str | None = None
    market_details: list[MarketMetadata]
    settlement_sources: list[SettlementSource]
    competition: str | None = None
    competition_scope: str | None = None


class GetEventForecastPercentilesHistoryResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    forecast_history: list[ForecastPercentilesPoint]


class GetSeriesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    series: Series


class GetSeriesListResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    series: list[Series]


class GetSeriesFeeChangesResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    series_fee_change_arr: list[SeriesFeeChange]


class GetMarketsResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    markets: list[Market]
    cursor: str


class GetMarketResponse(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market: Market
