"""WebSocket message models generated from the Kalshi AsyncAPI spec."""

# NOTE: Auto-generated by tools/generate_ws_models.py — do not edit manually.

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class Channel(str, Enum):
    """WebSocket subscription channels."""

    ORDERBOOK_DELTA = "orderbook_delta"
    """Real-time orderbook price level changes. Provides incremental updates to maintain a live orderbook."""

    TICKER = "ticker"
    """Market price, volume, and open interest updates."""

    TRADE = "trade"
    """Public trade notifications when trades occur."""

    FILL = "fill"
    """Your order fill notifications. Requires authentication."""

    MARKET_POSITIONS = "market_positions"
    """Real-time updates of your positions in markets. Requires authentication."""

    MARKET_LIFECYCLE_V2 = "market_lifecycle_v2"
    """Market state changes and event creation notifications."""

    MULTIVARIATE_MARKET_LIFECYCLE = "multivariate_market_lifecycle"
    """Multivariate event (MVE) market state changes and event creation notifications."""

    MULTIVARIATE = "multivariate"
    """Deprecated: this channel predates RFQs and should not be used for new integrations."""

    COMMUNICATIONS = "communications"
    """Real-time Request for Quote (RFQ) and quote notifications. Requires authentication."""

    ORDER_GROUP_UPDATES = "order_group_updates"
    """Real-time order group lifecycle and limit updates. Requires authentication."""

    USER_ORDERS = "user_orders"
    """Real-time order created and updated notifications. Requires authentication."""



class ErrorResponseMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    code: int = Field(..., description="Error code identifying the type of error: - 1: Unable to process message - General processing error - 2: Params required - Missing params object in command - 3: Channels required - Missing channels array in subscribe - 4: Subscription IDs required - Missing sids in unsubscribe - 5: Unknown command - Invalid command name - 6: Already subscribed - Duplicate subscription attempt - 7: Unknown subscription ID - Subscription ID not found - 8: Unknown channel name - Invalid channel in subscribe - 9: Authentication required - Channel requires authenticated connection - 10: Channel error - Channel-specific error - 11: Invalid parameter - Malformed parameter value - 12: Exactly one subscription ID is required - For update_subscription - 13: Unsupported action - Invalid action for update_subscription - 14: Market Ticker required - Missing market specification (market_ticker or market_id) - 15: Action required - Missing action in update_subscription - 16: Market not found - Invalid market_ticker or market_id - 17: Internal error - Server-side processing error - 18: Command timeout - Server timed out while processing command - 19: shard_factor must be > 0 - Invalid shard_factor - 20: shard_factor is required when shard_key is set - Missing shard_factor when shard_key is set - 21: shard_key must be >= 0 and < shard_factor - Invalid shard_key - 22: shard_factor must be <= 100 - shard_factor too large")
    msg: str = Field(..., description="Human-readable error message")
    market_id: str | None = Field(None, description="Market UUID if error is market-specific (optional)")
    market_ticker: str | None = Field(None, description="Market ticker if error is market-specific (optional)")


class EventFeeUpdateMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str = Field(..., description="Unique identifier for the event")
    fee_type_override: str | None = Field(None, description="Event fee type override. `null` when the override has been cleared.")
    fee_multiplier_override: float | None = Field(None, description="Event fee multiplier override. `null` when the override has been cleared.")


class EventLifecycleMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_ticker: str = Field(..., description="Unique identifier for the event being created")
    title: str = Field(..., description="Title of event")
    subtitle: str = Field(..., description="Subtitle of event")
    collateral_return_type: str = Field(..., description="Collateral return type, MECNET or DIRECNET of the event. Empty if there is no collateral return scheme for the event")
    series_ticker: str = Field(..., description="Series ticker for the event")
    strike_date: int | None = Field(None, description="Optional - Unix timestamp to indicate the strike date of the event if there is one")
    strike_period: str | None = Field(None, description="Optional - String to indicate the strike period of the event if there is one")


class FillMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    trade_id: str = Field(..., description="Unique identifier for fills. This is what you use to differentiate fills")
    order_id: str = Field(..., description="Unique identifier for orders. This is what you use to differentiate fills for different orders")
    market_ticker: str = Field(..., description="Unique identifier for markets. This is what you use to differentiate fills for different markets")
    is_taker: bool = Field(..., description="If you were a taker on this fill")
    side: str = Field(..., description="Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/order_direction). This field will not be removed before May 14, 2026.", deprecated=True)
    yes_price_dollars: str = Field(..., description="Price for the yes side of the fill in dollars")
    count_fp: str = Field(..., description="Fixed-point contracts filled (2 decimals)")
    fee_cost: str = Field(..., description="Exchange fee paid for this fill in fixed-point dollars")
    action: str = Field(..., description="Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/order_direction). This field will not be removed before May 14, 2026.", deprecated=True)
    ts: int = Field(..., description="Deprecated - Unix timestamp for when the update happened (in seconds). Use ts_ms instead.", deprecated=True)
    ts_ms: int = Field(..., description="Unix timestamp for when the update happened (in milliseconds)")
    client_order_id: str | None = Field(None, description="Optional client-provided order ID")
    post_position_fp: str = Field(..., description="Fixed-point position after the fill (2 decimals)")
    purchased_side: str = Field(..., description="Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/order_direction). This field will not be removed before May 14, 2026.", deprecated=True)
    outcome_side: str = Field(..., description="The outcome side this fill positioned the user for. buy-yes and sell-no produce 'yes'; buy-no and sell-yes produce 'no'.  `outcome_side` describes directional exposure only; it does not change the fill's price. A fill at price `p` with `outcome_side=no` is matched against an order at the same price `p` with `outcome_side=yes` — both parties trade at the same price, just on opposite directions.  `outcome_side` and `book_side` will become the canonical way to determine fill direction. The legacy `action` and `side` fields will be deprecated in a future release — please migrate to these new fields.")
    book_side: str = Field(..., description="Same directional bit as outcome_side in book vocabulary. 'bid' is equivalent to outcome_side 'yes'; 'ask' is equivalent to outcome_side 'no'.  `outcome_side` and `book_side` will become the canonical way to determine fill direction. The legacy `action` and `side` fields will be deprecated in a future release — please migrate to these new fields.")
    subaccount: int | None = Field(None, description="Optional subaccount number for the fill")


class MarketLifecycleV2Msg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_type: str = Field(..., description="Field to annotate which of the event type this event is for: - `created` - Market created - `activated` - Market activated - `deactivated` - Market deactivated - `close_date_updated` - Market close date updated - `determined` - Market determined - `settled` - Market settled - `price_level_structure_updated` - Market price level structure changed - `metadata_updated` - Market metadata updated (e.g. floor strike, yes_sub_title)")
    market_ticker: str = Field(..., description="Unique identifier for markets. This is what you use to differentiate updates for different markets")
    open_ts: int | None = Field(None, description="Optional - This key will ONLY exist when the market is created. Unix timestamp for when the market opened (in seconds)")
    close_ts: int | None = Field(None, description="Optional - This key will ONLY exist when the market is created OR when the close date is updated. Unix timestamp for when the market is scheduled to close (in seconds). Will be updated in case of early determination markets")
    result: str | None = Field(None, description="Optional - This key will ONLY exist when the market is determined. Result of the market")
    determination_ts: int | None = Field(None, description="Optional - This key will ONLY exist when the market is determined. Unix timestamp for when the market is determined (in seconds)")
    settlement_value: str | None = Field(None, description="Optional - This key will ONLY exist when the market is determined. Settlement value of the market in fixed-point dollars (e.g. \"0.5000\")")
    settled_ts: int | None = Field(None, description="Optional - This key will ONLY exist when the market is settled. Unix timestamp for when the market is settled (in seconds)")
    is_deactivated: bool | None = Field(None, description="Optional - This key will ONLY exist when the market is paused/unpaused. Boolean flag to indicate if trading is paused on an open market. This should only be interpreted for an open market")
    price_level_structure: str | None = Field(None, description="Optional - This key will exist when the market is created or when the price level structure is updated. The price level structure of the market")
    floor_strike: float | None = Field(None, description="Optional - This key will ONLY exist for metadata_updated events. The updated floor strike value for the market")
    yes_sub_title: str | None = Field(None, description="Optional - This key will ONLY exist for metadata_updated events. The updated yes subtitle for the market")
    additional_metadata: dict[str, Any] | None = Field(None, description="Optional - This key will be emitted when the market is created")


class MarketPositionMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_id: str = Field(..., description="User ID for the position")
    market_ticker: str = Field(..., description="Market ticker for the position")
    position_fp: str = Field(..., description="Fixed-point net position (2 decimals)")
    position_cost_dollars: str = Field(..., description="Current cost basis of the position as a fixed-point dollar string")
    realized_pnl_dollars: str = Field(..., description="Realized profit/loss as a fixed-point dollar string")
    fees_paid_dollars: str = Field(..., description="Total fees paid as a fixed-point dollar string")
    position_fee_cost_dollars: str = Field(..., description="Total position fee cost as a fixed-point dollar string")
    volume_fp: str = Field(..., description="Fixed-point total volume traded (2 decimals)")
    subaccount: int | None = Field(None, description="Optional subaccount number for the position")


class MultivariateLookupMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    collection_ticker: str
    event_ticker: str
    market_ticker: str
    selected_markets: list[dict[str, Any]]


class OkResponseMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_tickers: list[str] | None = Field(None, description="Full list of market tickers after update")
    market_ids: list[str] | None = Field(None, description="Full list of market IDs after update")


class OrderGroupUpdatesMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    event_type: str = Field(..., description="Order group event type")
    order_group_id: str = Field(..., description="Order group identifier")
    contracts_limit_fp: str | None = Field(None, description="Updated contracts limit in fixed-point (2 decimals). Present for \"created\" and \"limit_updated\" events only.")
    ts_ms: int = Field(..., description="Matching engine timestamp at which the event was processed, as Unix epoch milliseconds.")


class OrderbookDeltaMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    market_id: str
    price_dollars: str = Field(..., description="Price level in dollars")
    delta_fp: str = Field(..., description="Fixed-point contract delta (2 decimals)")
    side: str
    client_order_id: str | None = Field(None, description="Optional - Present only when you caused this orderbook change. Contains the client_order_id of your order that triggered this delta.")
    subaccount: int | None = Field(None, description="Optional - Present only when you caused this orderbook change and are using subaccounts. Contains the subaccount number of your order that triggered this delta.")
    ts: str | None = Field(None, description="Deprecated - Optional timestamp for when the orderbook change was recorded (RFC3339). Use ts_ms instead.", deprecated=True)
    ts_ms: int | None = Field(None, description="Optional - Unix timestamp for when the orderbook change was recorded (in milliseconds)")


class OrderbookSnapshotMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    market_id: str
    yes_dollars_fp: list[list[str]] | None = Field(None, description="Optional - This key will not exist if there are no Yes offers in the orderbook. Price levels represented as [price_in_dollars, contract_count_fp]. Format: [price_in_dollars, contract_count_fp]")
    no_dollars_fp: list[list[str]] | None = Field(None, description="Optional - Same format as \"yes_dollars_fp\" but for the NO side of the orderbook. This key will not exist if there are no No offers in the orderbook. Format: [price_in_dollars, contract_count_fp]")


class QuoteAcceptedMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quote_id: str = Field(..., description="Unique identifier for the quote")
    rfq_id: str = Field(..., description="Identifier of the RFQ this quote is for")
    quote_creator_id: str = Field(..., description="Public communications ID of the quote creator (anonymized)")
    market_ticker: str = Field(..., description="Market ticker for the quote")
    event_ticker: str | None = Field(None, description="Event ticker (optional)")
    yes_bid_dollars: str = Field(..., description="Yes side bid price in dollars")
    no_bid_dollars: str = Field(..., description="No side bid price in dollars")
    accepted_side: str | None = Field(None, description="Which side was accepted (yes/no) (optional)")
    contracts_accepted_fp: str | None = Field(None, description="Fixed-point contracts accepted (2 decimals) (optional)")
    yes_contracts_offered_fp: str | None = Field(None, description="Fixed-point yes contracts offered (2 decimals) (optional)")
    no_contracts_offered_fp: str | None = Field(None, description="Fixed-point no contracts offered (2 decimals) (optional)")
    rfq_target_cost_dollars: str | None = Field(None, description="Target cost from the RFQ in dollars (optional)")


class QuoteCreatedMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quote_id: str = Field(..., description="Unique identifier for the quote")
    rfq_id: str = Field(..., description="Identifier of the RFQ this quote is for")
    quote_creator_id: str = Field(..., description="Public communications ID of the quote creator (anonymized)")
    market_ticker: str = Field(..., description="Market ticker for the quote")
    event_ticker: str | None = Field(None, description="Event ticker (optional)")
    yes_bid_dollars: str = Field(..., description="Yes side bid price in dollars")
    no_bid_dollars: str = Field(..., description="No side bid price in dollars")
    yes_contracts_offered_fp: str | None = Field(None, description="Fixed-point yes contracts offered (2 decimals) (optional)")
    no_contracts_offered_fp: str | None = Field(None, description="Fixed-point no contracts offered (2 decimals) (optional)")
    rfq_target_cost_dollars: str | None = Field(None, description="Target cost from the RFQ in dollars (optional)")
    created_ts: str = Field(..., description="Timestamp when the quote was created")


class QuoteExecutedMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    quote_id: str = Field(..., description="Unique identifier for the quote that was executed")
    rfq_id: str = Field(..., description="Identifier of the RFQ this quote was for")
    quote_creator_id: str = Field(..., description="Anonymized identifier for the quote creator")
    rfq_creator_id: str = Field(..., description="Anonymized identifier for the RFQ creator")
    order_id: str = Field(..., description="Your order ID resulting from the quote execution. Use this to match with fill messages")
    client_order_id: str = Field(..., description="Your client order ID for the executed order. Use this to correlate with fill messages")
    market_ticker: str = Field(..., description="Market ticker for the executed quote")
    executed_ts: str = Field(..., description="Timestamp when the quote was executed and orders were placed")


class RfqCreatedMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(..., description="Unique identifier for the RFQ")
    creator_id: str = Field(..., description="Public communications ID of the RFQ creator (anonymized). Currently empty for rfq_created events.")
    market_ticker: str = Field(..., description="Market ticker for the RFQ")
    event_ticker: str | None = Field(None, description="Event ticker (optional)")
    contracts_fp: str | None = Field(None, description="Fixed-point contracts requested (2 decimals) (optional)")
    target_cost_dollars: str | None = Field(None, description="Target cost in dollars (optional)")
    created_ts: str = Field(..., description="Timestamp when the RFQ was created")
    mve_collection_ticker: str | None = Field(None, description="Multivariate event collection ticker (optional)")
    mve_selected_legs: list[dict[str, Any]] | None = Field(None, description="Selected legs for multivariate events (optional)")


class RfqDeletedMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: str = Field(..., description="Unique identifier for the RFQ")
    creator_id: str = Field(..., description="Public communications ID of the RFQ creator (anonymized)")
    market_ticker: str = Field(..., description="Market ticker for the RFQ")
    event_ticker: str | None = Field(None, description="Event ticker (optional)")
    contracts_fp: str | None = Field(None, description="Fixed-point contracts requested (2 decimals) (optional)")
    target_cost_dollars: str | None = Field(None, description="Target cost in dollars (optional)")
    deleted_ts: str = Field(..., description="Timestamp when the RFQ was deleted")


class SubscribedResponseMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    channel: str
    sid: int


class TickerMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    market_ticker: str
    market_id: str
    price_dollars: str = Field(..., description="Last traded price in dollars")
    yes_bid_dollars: str = Field(..., description="Best bid price for yes side in dollars")
    yes_ask_dollars: str = Field(..., description="Best ask price for yes side in dollars")
    volume_fp: str = Field(..., description="Fixed-point total contracts traded (2 decimals)")
    open_interest_fp: str = Field(..., description="Fixed-point open interest (2 decimals)")
    dollar_volume: int = Field(..., description="Number of dollars traded in the market so far")
    dollar_open_interest: int = Field(..., description="Number of dollars positioned in the market currently")
    yes_bid_size_fp: str = Field(..., description="Fixed-point contracts at best bid (2 decimals)")
    yes_ask_size_fp: str = Field(..., description="Fixed-point contracts at best ask (2 decimals)")
    last_trade_size_fp: str = Field(..., description="Fixed-point contracts in last trade (2 decimals)")
    ts: int = Field(..., description="Deprecated - Unix timestamp for when the update happened (in seconds). Use ts_ms instead.", deprecated=True)
    ts_ms: int = Field(..., description="Unix timestamp for when the update happened (in milliseconds)")
    time: str = Field(..., description="Deprecated - Timestamp for when the update happened (RFC3339). Use ts_ms instead.", deprecated=True)


class TradeMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    trade_id: str = Field(..., description="Unique identifier for the trade")
    market_ticker: str
    yes_price_dollars: str = Field(..., description="Yes side price in dollars")
    no_price_dollars: str = Field(..., description="No side price in dollars")
    count_fp: str = Field(..., description="Fixed-point contracts traded (2 decimals)")
    taker_side: str = Field(..., description="Deprecated. Use `taker_outcome_side` (or `taker_book_side`) instead. See [Order direction](/getting_started/order_direction). This field will not be removed before May 14, 2026.", deprecated=True)
    taker_outcome_side: str = Field(..., description="The outcome side the taker is positioned for. buy-yes and sell-no produce 'yes'; buy-no and sell-yes produce 'no'.  `taker_outcome_side` describes directional exposure only; it does not change the trade's price. A trade at price `p` with `taker_outcome_side=no` is matched against the maker at the same price `p` with the opposite direction — both parties trade at the same price.  `taker_outcome_side` and `taker_book_side` will become the canonical way to determine trade direction. The legacy `taker_side` field will be deprecated in a future release — please migrate to these new fields.")
    taker_book_side: str = Field(..., description="Same directional bit as taker_outcome_side in book vocabulary. 'bid' is equivalent to taker_outcome_side 'yes'; 'ask' is equivalent to taker_outcome_side 'no'.  `taker_outcome_side` and `taker_book_side` will become the canonical way to determine trade direction. The legacy `taker_side` field will be deprecated in a future release — please migrate to these new fields.")
    ts: int = Field(..., description="Deprecated - Unix timestamp in seconds. Use ts_ms instead.", deprecated=True)
    ts_ms: int = Field(..., description="Unix timestamp in milliseconds")


class UserOrderMsg(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    order_id: str = Field(..., description="Unique order identifier")
    user_id: str = Field(..., description="User identifier")
    ticker: str = Field(..., description="Market ticker for the order")
    status: str = Field(..., description="Current order status")
    side: str = Field(..., description="Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/order_direction). This field will not be removed before May 14, 2026.", deprecated=True)
    is_yes: bool = Field(..., description="Deprecated. Use `outcome_side` (or `book_side`) instead. See [Order direction](/getting_started/order_direction). This field will not be removed before May 14, 2026.", deprecated=True)
    outcome_side: str = Field(..., description="The outcome side this order is positioned for. buy-yes and sell-no produce 'yes'; buy-no and sell-yes produce 'no'.  `outcome_side` describes directional exposure only; it does not change the order's price. An order at price `p` with `outcome_side=no` is matched by an order at the same price `p` with `outcome_side=yes` — both parties trade at the same price, just on opposite directions.  `outcome_side` and `book_side` will become the canonical way to determine order direction. The legacy `action`, `side`, and `is_yes` fields will be deprecated in a future release — please migrate to these new fields.")
    book_side: str = Field(..., description="Same directional bit as outcome_side in book vocabulary. 'bid' is equivalent to outcome_side 'yes'; 'ask' is equivalent to outcome_side 'no'.  `outcome_side` and `book_side` will become the canonical way to determine order direction. The legacy `action`, `side`, and `is_yes` fields will be deprecated in a future release — please migrate to these new fields.")
    yes_price_dollars: str = Field(..., description="Yes price in fixed-point dollars (4 decimals)")
    fill_count_fp: str = Field(..., description="Number of contracts filled in fixed-point (2 decimals)")
    remaining_count_fp: str = Field(..., description="Number of contracts remaining in fixed-point (2 decimals)")
    initial_count_fp: str = Field(..., description="Initial number of contracts in fixed-point (2 decimals)")
    taker_fill_cost_dollars: str = Field(..., description="Taker fill cost in fixed-point dollars (4 decimals)")
    maker_fill_cost_dollars: str = Field(..., description="Maker fill cost in fixed-point dollars (4 decimals)")
    taker_fees_dollars: str = Field(..., description="Taker fees in fixed-point dollars (4 decimals).")
    maker_fees_dollars: str = Field(..., description="Maker fees in fixed-point dollars (4 decimals).")
    client_order_id: str = Field(..., description="Client-provided order identifier")
    order_group_id: str | None = Field(None, description="Order group identifier, if applicable")
    self_trade_prevention_type: str | None = Field(None, description="Self-trade prevention type")
    created_time: str = Field(..., description="Deprecated - Order creation time in RFC3339 format. Use created_ts_ms instead.", deprecated=True)
    created_ts_ms: int = Field(..., description="Order creation time as a Unix timestamp in milliseconds")
    last_update_time: str | None = Field(None, description="Deprecated - Last update time in RFC3339 format. Use last_updated_ts_ms instead.", deprecated=True)
    last_updated_ts_ms: int | None = Field(None, description="Last update time as a Unix timestamp in milliseconds")
    expiration_time: str | None = Field(None, description="Deprecated - Order expiration time in RFC3339 format. Use expiration_ts_ms instead.", deprecated=True)
    expiration_ts_ms: int | None = Field(None, description="Order expiration time as a Unix timestamp in milliseconds")
    subaccount_number: int | None = Field(None, description="Subaccount number (0 for primary, 1-32 for subaccounts)")


class ErrorResponsePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int | None = None
    type_: str = Field(..., alias="type")
    msg: ErrorResponseMsg


class EventFeeUpdatePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: EventFeeUpdateMsg


class EventLifecyclePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: EventLifecycleMsg


class FillPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: FillMsg


class ListSubscriptionsCommandPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int
    cmd: str


class ListSubscriptionsResponsePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int
    type_: str = Field(..., alias="type")
    msg: list[dict[str, Any]] = Field(..., description="List of active subscriptions")


class MarketLifecycleV2Payload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: MarketLifecycleV2Msg


class MarketPositionPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: MarketPositionMsg


class MultivariateLookupPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: MultivariateLookupMsg


class OkResponsePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int | None = None
    sid: int | None = None
    seq: int | None = None
    type_: str = Field(..., alias="type")
    msg: OkResponseMsg | None


class OrderGroupUpdatesPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    seq: int
    msg: OrderGroupUpdatesMsg


class OrderbookDeltaPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    seq: int
    msg: OrderbookDeltaMsg


class OrderbookSnapshotPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    seq: int
    msg: OrderbookSnapshotMsg


class QuoteAcceptedPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: QuoteAcceptedMsg


class QuoteCreatedPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: QuoteCreatedMsg


class QuoteExecutedPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: QuoteExecutedMsg


class RfqCreatedPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: RfqCreatedMsg


class RfqDeletedPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: RfqDeletedMsg


class SubscribeCommandPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int
    cmd: str
    params: dict[str, Any]


class SubscribedResponsePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int | None = None
    type_: str = Field(..., alias="type")
    msg: SubscribedResponseMsg


class TickerPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: TickerMsg


class TradePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: TradeMsg


class UnsubscribeCommandPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int
    cmd: str
    params: dict[str, Any]


class UnsubscribedResponsePayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int | None = None
    sid: int
    seq: int
    type_: str = Field(..., alias="type")


class UpdateSubscriptionCommandPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: int
    cmd: str
    params: dict[str, Any]


class UserOrderPayload(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    type_: str = Field(..., alias="type")
    sid: int
    msg: UserOrderMsg
